import { Link } from "react-router-dom";
import { CampButton, CampPhoto, GivingInvite, PageHero, PressLinks, ProgramChoices, StorySection, Sunrise } from "../components/site/CampElements";
import { usePageMetadata } from "../lib/metadata";
import { actionLinks } from "../content/actions";
import home from "../content/data/home.json";
import about from "../content/data/about.json";
import registration from "../content/data/registration.json";
import staff from "../content/data/staff.json";
import donate from "../content/data/donate.json";
import faq from "../content/data/faq.json";
import brand from "../content/data/brand.json";
import programs from "../content/data/programs.json";

function StaffInvite() {
  return <section className="camp-section"><div className="camp-wrap staff-invite"><div className="staff-invite__photo"><CampPhoto number={3} alt="Camp staff stand together wearing tie-dye Indigo Point shirts" /></div><div><p className="camp-eyebrow">For the grown-ups who get it.</p><h2>Be someone’s<br />favorite counselor.</h2><p className="camp-lead">Bring your skills, your ridiculous camp spirit, and your care for kids. Help build the kind of queer community you wish you’d had growing up.</p><CampButton to="/staff" variant="outline">Work at Indigo Point</CampButton></div></div></section>;
}

function PoolStory() {
  return <section className="camp-section camp-section--indigo"><div className="camp-wrap pool-story"><div className="pool-story__photo"><CampPhoto number={2} alt="Campers gather together in the swimming pool" /></div><div><p className="camp-eyebrow">The people make the place.</p><h2>You can see<br />a future here.</h2><div className="camp-prose"><p>The counselor who introduces you to your favorite band. The adult who helps you try something new. At Indigo Point, kids find queer heroes and role models in the people they spend every day with.</p><p>Some campers arrive sure they won’t swim. They’re used to feeling judged about their bodies. Here, surrounded by peers and counselors like them, getting into the pool can mean something much bigger.</p><blockquote>“Hope that is impossible to unsee.”<cite>Daniel Bogard · Co-founder</cite></blockquote><CampButton to="/donate" variant="sun">Help make it possible</CampButton></div></div></div></section>;
}

export function HomePage() {
  usePageMetadata("home");
  return <>
    <section className="poster-hero"><div className="camp-wrap poster-hero__grid"><div className="poster-copy"><p className="camp-eyebrow">{home.hero.eyebrow}</p><h1>Camp.<br />With your<br /><em>people.</em></h1><p className="camp-lead">{home.hero.summary}</p><div className="camp-actions"><CampButton to="/registration">Find your summer</CampButton><CampButton to="/camp-life" variant="outline">Take a look around</CampButton></div></div><div className="poster-photo"><Sunrise /><CampPhoto {...home.heroGallery[0]} eager /><span className="poster-stamp" aria-label={`${programs.community.campers} campers from ${programs.community.states} states`}>{programs.community.campers} KIDS.<br />{programs.community.states} STATES.<br />ONE CAMP.</span><span className="poster-sticker" aria-hidden="true">QUEER JOY, ALL SUMMER.</span><p className="photo-note">This is what summer is for.</p></div></div></section>
    <div className="camp-ticker"><span>{programs.dates}</span><span aria-hidden="true">✳</span><span>Queer joy. Real camp.</span><span aria-hidden="true">✳</span><Link to="/registration#scholarships">Scholarships available</Link></div>
    <section className="camp-section"><div className="camp-wrap"><div className="story-grid"><div><p className="camp-eyebrow">The days are full. So are our hearts.</p><h2>A lot of camp.<br />A lot of being<br />yourself.</h2></div><div className="camp-prose camp-prose--lead"><p>{home.sections[0].body}</p><CampButton to="/camp-life" variant="text">Get a feel for camp</CampButton></div></div><div className="camp-photo-strip"><figure><CampPhoto number={18} alt="Hands weave friendship bracelets beside an Indigo Point logo sticker" /><figcaption>Make something. Make a friend.</figcaption></figure><figure><CampPhoto number={9} alt="A camper reads a book in a hammock beneath the trees" /><figcaption>Queer joy has quiet moments, too.</figcaption></figure><figure><CampPhoto number={19} alt="A Progress Pride flag flies among the trees at camp" /><figcaption>Our flag. Our people. Our camp.</figcaption></figure></div></div></section>
    <PoolStory /><ProgramChoices /><GivingInvite /><StaffInvite /><div className="camp-wrap"><PressLinks /></div>
  </>;
}

export function CampLifePage() {
  usePageMetadata("campLife");
  return <><PageHero eyebrow="This is what summer is for." title={<>The very important<br />business of camp.</>} intro={about.campLife.summary} photo={{ number: 6, alt: "A camper raises their arms at the lake wearing a Be Gay Do Good shirt" }}><CampButton to="/registration">Come to camp</CampButton></PageHero>
    <section className="camp-section"><div className="camp-wrap"><div className="section-heading"><div><p className="camp-eyebrow">Try something. Find your thing.</p><h2>Full days.<br />Your kind of fun.</h2></div><p>Campers try activities with their bunk and choose others that fit their own interests.</p></div><div className="activity-grid">{[{title:"Jump in.",number:11,alt:"Two campers jump into the lake",body:"Swimming, canoeing, kayaking, and time at the waterfront."},{title:"Make a little mess.",number:18,alt:"Hands braid colorful friendship bracelets",body:"Arts and crafts, music, drama, dance, and creative writing."},{title:"Go a little further.",number:8,alt:"A group poses together in the woods",body:"Archery, climbing, ropes courses, hiking, and camp games."},{title:"Find your own pace.",number:9,alt:"A camper reads in a hammock",body:"Books, rest time, and space to recharge between adventures."}].map(item=><article key={item.title}><CampPhoto {...item}/><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></div></section>
    <StorySection heading={about.campLife.heading} body="A camp day has a rhythm: meals together, activity periods, time to rest, and something to look forward to in the evening." eyebrow="A day at Indigo Point" color="yellow"><ol className="camp-timeline">{about.campLife.schedule.map(item=><li key={item.time}><span>{item.time}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ol></StorySection>
    <section className="camp-section"><div className="camp-wrap story-photo-grid"><div><p className="camp-eyebrow">Yes, there’s a queer prom.</p><h2>Some nights<br />you wait all year for.</h2><div className="camp-prose"><p>Campfires. Bunk nights. Capture the flag. Silent discos. And Queer Prom, outdoors and camp-style, with room to show up however you feel like yourself.</p><p>The best traditions are the ones you share with people who remember them with you.</p></div></div><CampPhoto number={17} alt="Campers dance beneath a rainbow disco ball" /></div></section><PoolStory /><ProgramChoices /></>;
}

export function RegistrationPage() {
  usePageMetadata("registration");
  return <><PageHero eyebrow={`Overnight camp / Summer ${programs.season}`} title={<>See you<br />at camp.</>} intro={registration.intro} photo={{ number:11,alt:"Two campers leap from the dock into the water" }}><CampButton href={actionLinks.register.href}>Register for camp</CampButton><CampButton to="/families" variant="outline">For families</CampButton></PageHero>
    <section className="camp-section"><div className="camp-wrap"><p className="camp-eyebrow">Pick your summer.</p><h2>Camp plans, made clear.</h2><div className="session-grid"><article><span className="session-label">The full camp experience</span><h3>Two weeks.</h3><p className="session-date">{programs.dates}</p><dl><div><dt>Who</dt><dd>{programs.grades}</dd></div><div><dt>Tuition</dt><dd>{programs.tuition}</dd></div><div><dt>Where</dt><dd>The Midwest</dd></div></dl><p>Swimming, campfires, arts and crafts, camp traditions, and time to build friendships.</p><CampButton href={actionLinks.register.href}>Register for two weeks</CampButton></article><article><span className="session-label">A first taste of camp</span><h3>One week.</h3><p className="session-date">{programs.shortSession.dates}</p><dl><div><dt>Who</dt><dd>{programs.shortSession.grades}</dd></div><div><dt>Tuition</dt><dd>{programs.shortSession.tuition}</dd></div><div><dt>For</dt><dd>{programs.shortSession.eligibility}</dd></div></dl><p>A shorter option for younger campers coming to Indigo Point for the first time.</p><CampButton href={actionLinks.register.href} variant="outline">Register for one week</CampButton></article></div><p className="camp-small session-footnote">Grades refer to the {programs.season}–{programs.season + 1} school year. A {programs.cit.grades.toLowerCase()} CIT program is also listed for {programs.cit.dates}, with tuition of {programs.cit.tuition}. <a href="mailto:dan@campindigopoint.org?subject=CIT%20program">Ask Dan about the CIT program ↗</a></p></div></section>
    <StorySection id="scholarships" eyebrow="Cost shouldn’t keep a kid from camp." heading={registration.affordability.heading} body={registration.affordability.summary} bullets={registration.affordability.details} color="pink"><CampButton href="mailto:dan@campindigopoint.org?subject=Camp%20scholarships">Talk to Dan about scholarships</CampButton></StorySection>
    <StorySection eyebrow="From here to camp." heading={registration.handoff.heading} bullets={registration.handoff.bullets}><CampButton href={actionLinks.register.href}>Open registration</CampButton><p className="camp-small">Registration opens in our external registration system.</p></StorySection><StorySection heading="Still deciding?" body="Get a feel for camp life, read about bunks and community care, or talk with us about your camper." color="blue"><div className="camp-actions"><CampButton to="/camp-life">Explore camp life</CampButton><CampButton to="/families" variant="outline">Family information</CampButton></div></StorySection></>;
}

export function ColoradoPage() {
  usePageMetadata("colorado");
  const co = programs.colorado;
  const contact = `mailto:${co.contact}?subject=Colorado%20teen%20program`;
  return <><PageHero eyebrow="Indigo Point / Colorado teen program" title={<>Same people.<br />New heights.</>} intro={co.intro} photo={{ number:12,alt:"Camp community stands arm in arm beside a mountain lake" }} color="pink"><CampButton href={co.registrationUrl || contact}>{co.registrationUrl ? "Register for Colorado" : "Ask about Colorado"}</CampButton></PageHero>
    <StorySection eyebrow="Camp, with a different view." heading="Take your people on an adventure." body={co.description}><ul className="camp-list">{co.activities.map(activity=><li key={activity}>{activity}</li>)}</ul><p className="camp-small">Activities vary by trip; ask us about the next itinerary.</p></StorySection>
    <section className="camp-section camp-section--blue"><div className="camp-wrap story-grid"><div><p className="camp-eyebrow">Plan the next adventure.</p><h2>Let’s talk<br />Colorado.</h2></div><div className="camp-prose"><p>{co.nextStep}</p><dl className="detail-list"><div><dt>Dates</dt><dd>{co.dates || "Contact us for the next dates"}</dd></div><div><dt>Eligibility</dt><dd>{co.grades || "Teen program — ask about the next trip’s grade range"}</dd></div><div><dt>Tuition & scholarships</dt><dd>{co.tuition || "Contact us to discuss tuition and financial support"}</dd></div></dl><CampButton href={co.registrationUrl || contact}>{co.registrationUrl ? "Register for Colorado" : "Get Colorado details"}</CampButton></div></div></section>
    <StorySection heading="A future you can see." body="The setting changes. What matters stays the same: time with other queer young people, and queer adults who help make new experiences possible."><CampButton to="/registration" variant="outline">Also explore overnight camp</CampButton></StorySection><GivingInvite /></>;
}

export function FamiliesPage() {
  usePageMetadata("families");
  return <><PageHero className="family-hero" eyebrow="For the people sending their people." title={<>A big summer.<br />A little reassurance.</>} intro="Choosing camp is a big decision. Here’s how we think about everyday camp life, care, and helping your child feel at home." photo={{ number:4,alt:"Campers spend an afternoon together by the water" }}><CampButton to="/registration">Dates & registration</CampButton><CampButton to="/contact" variant="outline">Talk with us</CampButton></PageHero>
    <StorySection heading={registration.accommodations.heading} body={registration.accommodations.body} bullets={registration.accommodations.details} eyebrow="Bunks, bathrooms, and belonging." />
    <StorySection id="community-care" heading="Care is part of camp." body="Our counselors are part of campers’ daily lives, in the bunks and at activities. Our community care team supports the mental, emotional, and social side of being away from home." color="blue"><p>Camp can be busy, loud, exciting, and occasionally overwhelming. Rest time and quieter spaces matter, too.</p><p>Indigo Point is an overnight summer camp, not a therapeutic program. Before registering, talk with us about medication, access needs, sensory needs, or other support your camper may need. We can discuss what camp can provide and whether it is a good fit.</p><CampButton href="mailto:shira@campindigopoint.org?subject=Camper%20care%20and%20accommodations">Discuss care & accommodations</CampButton></StorySection>
    <StorySection heading="Room to be a kid." body="Queerness is something campers and staff have in common. That leaves more room for friendships, new activities, and being yourself without having to explain everything." eyebrow="Ordinary camp. Extraordinary community."><p>Campers are called by their names and pronouns. Bunking takes grade level and campers’ comfort into account. Queer adults are there as counselors, leaders, and role models.</p><p>Our camping roots are Jewish; Indigo Point welcomes campers of all faiths and none.</p></StorySection>
    <StorySection heading="More face-to-face time." body="Camp is a chance to make friends in person. Campers leave phones, internet, and video games behind. Music players, audiobooks, and digital cameras are allowed." color="yellow"><p>For questions about staying in touch, health forms, packing, or travel arrangements, contact us. Our team can help you prepare for camp.</p><CampButton to="/contact">Ask a family question</CampButton></StorySection><FaqSection items={faq.items.filter(item=>item.category==="Families")} /><StorySection heading="Camp should be within reach." body={registration.affordability.promise} color="pink"><CampButton to="/registration#scholarships">Scholarships & registration</CampButton></StorySection></>;
}

export function DonatePage() {
  usePageMetadata("donate");
  return <><PageHero className="donation-hero" eyebrow="Give a kid camp." title={<>Marshmallows.<br />Role models.<br />Lives changed.</>} intro={donate.intro} photo={{ number:13,alt:"A camper wears rainbow and trans pride flags at a camp gathering" }} color="pink"><CampButton href={actionLinks.donate.href}>Donate to Indigo Point</CampButton></PageHero>
    <StorySection heading={donate.lifeline.heading} body={donate.lifeline.body} bullets={donate.lifeline.bullets} eyebrow="What your support makes possible." />
    <section className="camp-section camp-section--indigo"><div className="camp-wrap impact-strip"><div><strong>{programs.community.campers}</strong><span>Campers in our community</span></div><div><strong>{programs.community.states}</strong><span>States represented</span></div><p>Kids come from across the country to spend their summer with peers and queer adults who get them.</p></div></section>
    <StorySection heading={donate.ancestors.heading} body={donate.ancestors.body} bullets={donate.ancestors.details} color="blue" />
    <StorySection id="scholarships" heading="Help get a kid here." body="Scholarships put camp within reach. Your gift supports access to camp and the people and experiences that make it possible." color="yellow"><p>Full tuition for our two-week 2027 overnight session is {programs.tuition}. A gift of any size helps us meet scholarship needs and support camp.</p><div className="camp-actions"><CampButton href={actionLinks.donate.href}>Support camp</CampButton><CampButton href="mailto:dan@campindigopoint.org?subject=Scholarship%20or%20foundation%20support" variant="outline">Discuss a larger gift</CampButton></div></StorySection>
    <StorySection heading={donate.partnersInJoy.heading} body={donate.partnersInJoy.body} bullets={donate.partnersInJoy.bullets}><CampButton href="mailto:dan@campindigopoint.org?subject=Partnering%20with%20Indigo%20Point">Talk about supporting camp</CampButton></StorySection>
    <StorySection heading={donate.fiscalSponsorship.heading} body={donate.fiscalSponsorship.body} bullets={donate.fiscalSponsorship.details} color="pink"><CampButton href={actionLinks.donate.href}>Make your gift</CampButton></StorySection></>;
}

export function StaffPage() {
  usePageMetadata("staff");
  return <><PageHero eyebrow="Work at Indigo Point." title={<>Be someone’s<br />favorite counselor.</>} intro={staff.intro} photo={{number:3,alt:"Staff smile together in colorful Indigo Point camp shirts"}}><CampButton href={actionLinks.apply.href}>{actionLinks.apply.label}</CampButton></PageHero>
    <StorySection heading={staff.theMagic.heading} body={staff.theMagic.body} bullets={staff.theMagic.bullets} eyebrow="You’re part of what’s possible." />
    <StorySection heading={staff.theMud.heading} body={staff.theMud.body} bullets={staff.theMud.bullets} color="yellow" />
    <section className="camp-section"><div className="camp-wrap"><p className="camp-eyebrow">Different skills. Shared responsibility.</p><h2>Find your role.</h2><div className="role-grid">{[{title:"Counselors",body:"Live and move through the day with your bunk. Support campers, lead activities, and help make the small moments count."},{title:"Activity specialists",body:"Bring expertise in the arts, waterfront, sports, or adventure activities. Teach skills and participate in bunk life."},{title:"Unit heads",body:"Support counselors, mentor the team, plan age-appropriate programming, and help solve problems."},{title:"Care & wellness",body:"Bring professional nursing, mental health, or wellness experience. Talk with Shira about the roles and qualifications camp needs."}].map(role=><article key={role.title}><h3>{role.title}</h3><p>{role.body}</p></article>)}</div></div></section>
    <StorySection heading={staff.theCommunity.heading} body={staff.theCommunity.body} color="pink"><p>{staff.theCommunity.rolesOverview}</p></StorySection>
    <StorySection heading={staff.applicationProcess.heading} bullets={staff.applicationProcess.steps}><p>Ask about role availability, compensation, staff dates, training, and qualifications before committing. Our team will share current details directly.</p><CampButton href={actionLinks.apply.href}>{actionLinks.apply.label}</CampButton></StorySection></>;
}

export function AboutPage() {
  usePageMetadata("about");
  return <><PageHero eyebrow="Our story." title={<>A world kids<br />can believe in.</>} intro={about.history.body} photo={{number:14,alt:"A camp jacket painted with the words Trans Liberation Now"}} /><StorySection heading="Built by people who love camp." body="Indigo Point grew from a shared love of Jewish summer camping and the conviction that queer and trans kids deserve that kind of community." eyebrow="Our roots." ><p>Daniel Bogard, Shira Berkowitz, and Dan Grabel helped turn that vision into camp. The first summer was in 2022. Today, our community brings together 150 LGBTQ+ campers from 33 states.</p><p>Campers see themselves in the people around them: friends, counselors, and queer grown-ups with lives and futures of their own.</p></StorySection><StorySection heading="What we care about." color="blue"><div className="values-list">{brand.brandValues.map(value=><div key={value.name}><h3>{value.name}</h3><p>{value.description}</p></div>)}</div></StorySection><section className="camp-section" id="press"><div className="camp-wrap"><p className="camp-eyebrow">Spend a little time with our story.</p><h2>Camp, in the news.</h2><PressLinks full /></div></section><GivingInvite /></>;
}

function FaqSection({ items = faq.items }) {
  return <section className="camp-section"><div className="camp-wrap faq-grid"><div><p className="camp-eyebrow">A few things you might be wondering.</p><h2>Good questions.</h2><p>Something else on your mind? <Link to="/contact">Talk with us ↗</Link></p></div><div className="faq-list">{items.map(item=><details key={item.question}><summary>{item.question}<span aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></div></section>;
}

export function FaqPage() {
  usePageMetadata("faq");
  return <><PageHero eyebrow="Questions & answers." title={<>Let’s clear<br />a few things up.</>} intro={faq.intro} /><FaqSection /><ProgramChoices /></>;
}

export function ContactPage() {
  usePageMetadata("contact");
  return <><PageHero eyebrow="Talk with us." title={<>Hi. We’re glad<br />you’re here.</>} intro="Choosing camp, joining the staff, or helping a kid get here? We’d love to hear from you." color="pink" /><section className="camp-section"><div className="camp-wrap contact-grid">{brand.contactDirectory.map(contact=><article key={contact.email}><p className="camp-eyebrow">{contact.intent}</p><h2>{contact.name}</h2><p>{contact.role}</p><a href={`mailto:${contact.email}`}>{contact.email} ↗</a>{contact.phone && <a href={`tel:${contact.phone.replace(/[^0-9]/g,"")}`}>{contact.phone}</a>}</article>)}</div></section><StorySection heading="Thinking about Colorado?" body="Our teen program is a separate opportunity. Ask us about the next dates, eligibility, travel details, and financial support." color="blue"><CampButton href={`mailto:${programs.colorado.contact}?subject=Colorado%20teen%20program`}>Ask about Colorado</CampButton></StorySection><section className="camp-section"><div className="camp-wrap"><h2>Get to know us.</h2><PressLinks full /></div></section></>;
}

export function NotFoundPage() {
  usePageMetadata("notFound");
  return <PageHero eyebrow="A little off the trail." title="Let’s get you back to camp." intro="That page isn’t here. You can head home, explore camp, or get in touch."><CampButton to="/">Back to the homepage</CampButton><CampButton to="/contact" variant="outline">Contact us</CampButton></PageHero>;
}


